# -*- coding: utf-8 -*-
"""compare_interpolation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hk-Uu8JhuOFAB_td5D_7bRB0NnU7fy3H
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/gdrive')
# %cd gdrive/My\Drive/Mythesis

!pip install pandas

!pip install xlrd==2.0.1

!pip install pyproj

!pip install rasterio

!pip install plot_model

!pip install livelossplot

# Required libraries

import numpy as np
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from scipy import stats
import pandas as pd
import  pyproj
import rasterio as rio
import numpy as np
from sklearn.model_selection import train_test_split
import csv
import tensorflow as tf
from tensorflow import keras as ks
from keras.models import Sequential
from tensorflow.keras.optimizers import Adam, SGD, Adadelta
from keras.regularizers import l2 , l1
from keras import regularizers
from sklearn.model_selection import train_test_split
from keras.layers import Dense, Conv2D, Flatten, BatchNormalization, Activation, MaxPooling2D, Dropout, AveragePooling2D, GlobalMaxPooling2D
import livelossplot
import keras
import tensorflow as tf
import matplotlib.pyplot as plt
import os
import json
from tensorflow.keras.callbacks import ModelCheckpoint, LambdaCallback
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
import cv2

"""# **Comparison between CNN and Traditional interpolation methods**





"""

# load PSs
dftrain = pd.read_csv('pstrain.csv')

pred_train=dftrain['Prediction']

dftest = pd.read_csv('pstest.csv')

pred_test=dftest['Prediction']

# # IDW
# df_train_I = pd.read_excel('IDW_train.xls')
# df_test_I  = pd.read_excel('IDW_test.xls')

# IDW_train = df_train_I['IDW']
# IDW_test  = df_test_I ['IDW']

# # RBF
# df_train_R = pd.read_excel('RBF_train.xls')
# df_test_R  = pd.read_excel('RBF_test.xls')

# RBF_train = df_train_I['RBF']
# RBF_test  = df_test_I ['RBF']

# #Kriging
# df_train_K = pd.read_excel('Kriging_train.xls')
# df_test_K  = pd.read_excel('Kriging_test.xls')

# kriging_train = df_train_I['kriging']
# kriging_test  = df_test_I ['krifing']

"""# **Root Mean Squared Error (RMSE)**"""

# Function to calculate Root Mean Squared Error (RMSE)
def calculate_rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))
#_____________________________________ model RMSE__________________________________

# Assuming you have y_train_true, y_train_pred, y_test_true, y_test_pred loaded

# Calculate RMSE for training set
rmse_train = calculate_rmse(y_train2 , pred_train)

# Calculate RMSE for test set
rmse_test = calculate_rmse(y_test , pred_test)

print(f"Model RMSE for training set: {rmse_train}")
print(f"Model RMSE for test set: {rmse_test}")
# #_____________________________________ IDW RMSE__________________________________

# # Calculate RMSE for training set
# rmse_trainI = calculate_rmse(y_train2 - IDW_train)

# # Calculate RMSE for test set
# rmse_testI  = calculate_rmse(y_test - IDW_test)

# print(f"Model RMSE for training set: {rmse_trainI}")
# print(f"Model RMSE for test set: {rmse_testI}")


# #_____________________________________ RBF RMSE__________________________________

# # Calculate RMSE for training set
# rmse_trainR = calculate_rmse(y_train2 - RBF_train)

# # Calculate RMSE for test set
# rmse_testR  = calculate_rmse(y_test - RBF_test)

# print(f"Model RMSE for training set: {rmse_trainR}")
# print(f"Model RMSE for test set: {rmse_testR}")


# #_____________________________________ Kriging RMSE__________________________________


# # Calculate RMSE for training set
# rmse_trainK = calculate_rmse(y_train2 - kriging_train)

# # Calculate RMSE for test set
# rmse_testK  = calculate_rmse(y_test - kriging_test)

# print(f"Model RMSE for training set: {rmse_trainK}")
# print(f"Model RMSE for test set: {rmse_testK}")

"""# **R-squared (R2 score)**"""

# Function to calculate R-squared
def calculate_R2(y_true, y_pred):
    return r2_score(y_true, y_pred)
#_____________________________________ model R2__________________________________

# Assuming you have y_train_true, y_train_pred, y_test_true, y_test_pred loaded

# Calculate R2 for training set
R2_train = calculate_R2(y_train2 , pred_train)

# Calculate R2 for test set
R2_test = calculate_R2(y_test , pred_test)

print(f"Model R2 for training set: {R2_train}")
print(f"Model R2 for test set: {R2_test}")
# #_____________________________________ IDW R2__________________________________

# # Calculate R2 for training set
# R2_trainI = calculate_R2(y_train2 - IDW_train)

# # Calculate R2 for test set
# R2_testI  = calculate_R2(y_test - IDW_test)

# print(f"IDW R2 for training set: {R2_trainI}")
# print(f"IDW R2 for test set: {R2_testI}")


# #_____________________________________ RBF R2__________________________________

# # Calculate R2 for training set
# R2_trainR = calculate_R2(y_train2 - RBF_train)

# # Calculate R2 for test set
# R2_testR  = calculate_R2(y_test - RBF_test)

# print(f"RBF R2 for training set: {R2_trainR}")
# print(f"RBF R2 for test set: {R2_testR}")


# #_____________________________________ Kriging R2__________________________________


# # Calculate R2 for training set
# R2_trainK = calculate_R2(y_train2 - kriging_train)

# # Calculate R2 for test set
# R2_testK  = calculate_R2(y_test - kriging_test)

# print(f"kriging R2 for training set: {R2_trainK}")
# print(f"kriging R2 for test set: {R2_testK}")

"""# **Mean Absolute Error (MAE)**"""

# Function to calculate Mean Absolute Error (MAE)
def calculate_MAE(y_true, y_pred):
    return mean_absolute_error(y_true, y_pred)
#_____________________________________ model MAE__________________________________

# Assuming you have y_train_true, y_train_pred, y_test_true, y_test_pred loaded

# Calculate MAE for training set
MAE_train = calculate_MAE(y_train2 , pred_train)

# Calculate MAE for test set
MAE_test = calculate_MAE(y_test , pred_test)

print(f"Model MAE for training set: {MAE_train}")
print(f"Model MAE for test set: {MAE_test}")
# #_____________________________________ IDW MAE__________________________________

# # Calculate MAE for training set
# MAE_trainI = calculate_MAE(y_train2 - IDW_train)

# # Calculate MAE for test set
# MAE_testI  = calculate_MAE(y_test - IDW_test)

# print(f"IDW MAE  for training set: {MAE_trainI}")
# print(f"IDW MAE  for test set: {MAE_testI}")


# #_____________________________________ RBF MAE __________________________________

# # Calculate MAE  for training set
# MAE _trainR = calculate_MAE (y_train2 - RBF_train)

# # Calculate MAE for test set
# MAE _testR  = calculate_MAE (y_test - RBF_test)

# print(f"RBF MAE  for training set: {MAE _trainR}")
# print(f"RBF MAE  for test set: {MAE _testR}")


# #_____________________________________ Kriging MAE __________________________________


# # Calculate MAE  for training set
# MAE _trainK = calculate_MAE (y_train2 - kriging_train)

# # Calculate MAE  for test set
# MAE _testK  = calculate_MAE (y_test - kriging_test)

# print(f"kriging MAE  for training set: {MAE _trainK}")
# print(f"kriging MAE  for test set: {MAE _testK}")

"""# **Perform statistical tests:**

T-test or ANOVA to compare the performance metrics between the CNN model and Kriging.
"""

# Perform statistical tests (t-tests or ANOVA)
#_______________________________Kriging_______________________________

#  t-test for RMSE
t_statistic, p_value = stats.ttest_ind(rmse_test, rmse_testK)
print("\nStatistical significance test (t-test) for RMSE:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")


#  t-test for R2

t_statistic, p_value = stats.ttest_ind(R2_test, R2_testK)
print("\nStatistical significance test (t-test) for R2:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

#  t-test for MAE

t_statistic, p_value = stats.ttest_ind(MAE_test, rmse_testK)
print("\nStatistical significance test (t-test) for MAE:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

#_______________________________IDW_______________________________

#  t-test for RMSE
t_statistic, p_value = stats.ttest_ind(rmse_test, rmse_testI)
print("\nStatistical significance test (t-test) for RMSE:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")


#  t-test for R2

t_statistic, p_value = stats.ttest_ind(R2_test, R2_testI)
print("\nStatistical significance test (t-test) for R2:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

#  t-test for MAE

t_statistic, p_value = stats.ttest_ind(MAE_test, MAE_testI)
print("\nStatistical significance test (t-test) for MAE:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

#_______________________________RBF_______________________________

#  t-test for RMSE
t_statistic, p_value = stats.ttest_ind(rmse_test, rmse_testR)
print("\nStatistical significance test (t-test) for RMSE:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")


#  t-test for R2

t_statistic, p_value = stats.ttest_ind(R2_test, R2_testR)
print("\nStatistical significance test (t-test) for R2:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

#  t-test for MAE

t_statistic, p_value = stats.ttest_ind(MAE_test, MAE_testR)
print("\nStatistical significance test (t-test) for MAE:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")