# -*- coding: utf-8 -*-
"""predict_subsidence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fYFXaRTn6_zR4GK-3zeg4UnSJTeuYReZ
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/gdrive')
# %cd gdrive/My\Drive/Mythesis

!pip install rasterio

# Required libraries

import numpy as np
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from scipy import stats
import rasterio as rio
import numpy as np
from sklearn.model_selection import train_test_split
import csv
import tensorflow as tf
from tensorflow import keras as ks
from keras.models import Sequential
from tensorflow.keras.optimizers import Adam, SGD, Adadelta
from keras.regularizers import l2 , l1
from keras import regularizers
from sklearn.model_selection import train_test_split
import os
from keras.models import load_model
from keras import metrics
import keras
import tensorflow as tf
import matplotlib.pyplot as plt
import os
import json
from tensorflow.keras.callbacks import ModelCheckpoint, LambdaCallback
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
import cv2
import time

ndvi_1     =rio.open('NDVI_aligned.tif')
dist_1     =rio.open('distwells_aligned.tif')
elevation_1=rio.open('Elevation_aligned.tif')
twi_1      =rio.open('TWI_aligned.tif')
spi_1      =rio.open('SPI_aligned.tif')
slope_1    =rio.open('slope_aligned.tif')
landuse_1  =rio.open('landuse_aligned.tif')
water_1  =rio.open('watertable_trimmed.tif')
aspect_1  =rio.open('aspect_aligned.tif')

ndvi_2      = ndvi_1.read(1)
dist_2      = dist_1.read(1)
elevation_2 = elevation_1.read(1)
twi_2       = twi_1.read(1)
spi_2       = spi_1.read(1)
slope_2     = slope_1.read(1)
landuse_2   = landuse_1.read(1)
water_2     = water_1.read(1)
aspect_2    = aspect_1.read(1)


# normalize data
scaler = MinMaxScaler(feature_range=(0,1))

scaler.fit(ndvi_2)
ndvi_normalized      = scaler.transform(ndvi_2)

scaler.fit(dist_2)
dist_normalized      = scaler.transform(dist_2)


scaler.fit(elevation_2)
elevation_normalized = scaler.transform(elevation_2)

scaler.fit(twi_2)
twi_normalized       = scaler.transform(twi_2)

scaler.fit(slope_2)
slope_normalized     = scaler.transform(slope_2)

scaler.fit(landuse_2)
landuse_normalized   = scaler.transform(landuse_2)

scaler.fit(spi_2)
spi_normalized      = scaler.transform(spi_2)

scaler.fit(water_2)
water_normalized      = scaler.transform(water_2)

scaler.fit(aspect_2)
aspect_normalized      = scaler.transform(aspect_2)
aspect_normalized.shape

# np.max(water_normalized),np.min(water_normalized)

# Open the GeoTIFF
with rio.open('aspect_aligned.tif') as src:
    aspect = src.read(1)  # read band 1, for example
    transform = src.transform       # affine transform matrix
    profile = src.profile.copy()  # get metadata (CRS, transform, dtype, etc.)

    pxls = []
    rows, cols = aspect.shape

    for row in range(rows):
        for col in range(cols):
            if 15 < row < 3028 and 15 < col < 3149:
                # Convert pixel (col, row) to spatial coords (x, y)
                utmx, utmy = transform * (col, row)  # note order: col, row

                pxls.append([row, col, utmx, utmy])

    print(f"Total pixels selected: {len(pxls)}")

# row, col, utmx, utmy = pxls [0]
# ndvi_1.index(utmx,utmy),row,col,aspect_1.index(utmx,utmy),elevation_1.index(utmx,utmy)

model_path = 'Bestmodel.h5'  # Update this to the correct path if needed

# Check if the file exists before loading
if os.path.exists(model_path):
    # Define custom objects
    custom_objects = {
        'mse': metrics.mean_squared_error,  # Add other custom objects if necessary
    }

    # Load the model with custom objects
    model = load_model(model_path, custom_objects=custom_objects)
    print("Model loaded successfully.")
else:
    print(f"The file {model_path} does not exist.")

current_batch_size = 60000

data_ndvi      = np.zeros([current_batch_size,30,30],dtype='float32')
data_dist      = np.zeros([current_batch_size,30,30],dtype='float32')
data_elevation = np.zeros([current_batch_size,30,30],dtype='float32')
data_twi       = np.zeros([current_batch_size,30,30],dtype='float32')
data_slope     = np.zeros([current_batch_size,30,30],dtype='float32')
data_landuse   = np.zeros([current_batch_size,30,30],dtype='float32')
data_spi       = np.zeros([current_batch_size,30,30],dtype='float32')
data_aspect    = np.zeros([current_batch_size,30,30],dtype='float32')
data_water     = np.zeros([current_batch_size,30,30],dtype='float32')

c=0

for i in range(current_batch_size):

      ndvi_w      = ndvi_normalized     [pxls[i][0]-15:pxls[i][0]+15      , pxls[i][1]-15:pxls[i][1]+15]
      dist_w      = dist_normalized     [pxls[i][0]-15:pxls[i][0]+15      , pxls[i][1]-15:pxls[i][1]+15]
      elevation_w = elevation_normalized[pxls[i][0]-15:pxls[i][0]+15      , pxls[i][1]-15:pxls[i][1]+15]
      slope_w     = slope_normalized    [pxls[i][0]-15:pxls[i][0]+15      , pxls[i][1]-15:pxls[i][1]+15]
      twi_w       = twi_normalized      [pxls[i][0]-15:pxls[i][0]+15      , pxls[i][1]-15:pxls[i][1]+15]
      landuse_w   = landuse_normalized  [pxls[i][0]-15:pxls[i][0]+15      , pxls[i][1]-15:pxls[i][1]+15]
      spi_w       = spi_normalized      [pxls[i][0]-15:pxls[i][0]+15      , pxls[i][1]-15:pxls[i][1]+15]
      water_w     = water_normalized    [pxls[i][0]-15:pxls[i][0]+15      , pxls[i][1]-15:pxls[i][1]+15]
      aspect_w    = aspect_normalized   [pxls[i][0]-15:pxls[i][0]+15      , pxls[i][1]-15:pxls[i][1]+15]

      data_ndvi[c]     = ndvi_w
      data_dist[c]     = dist_w
      data_elevation[c]= elevation_w
      data_twi[c]      = twi_w
      data_slope[c]    = slope_w
      data_landuse[c]  = landuse_w
      data_spi[c]      = spi_w
      data_water[c]    = water_w
      data_aspect[c]   = aspect_w
      c=c+1
# # Create 3D input matrix [ 30 row *30 column *6 channel]
# # remember that we have 47209 sample
print(data_dist[0])
Data=np.zeros([current_batch_size,9,30,30])# sample:len(u_in_all), channels(features):9, row:30, column:30
for i in range(current_batch_size):
    Data[i,0:9,:,:]=[data_dist[i],data_elevation[i],data_ndvi[i], data_slope[i], data_landuse[i], data_twi[i],data_spi[i],data_aspect[i],data_water[i]]

data = Data.reshape(current_batch_size, 30, 30, 9)
# np.save('DATA2.npy',data)
# data= np.load('DATA.npy')
# data = data.reshape(60000, 30, 30, 9)
# pred_data=model.predict(data)
#


# Prepare the predata list
# predata = []
# for i in range(60000):
#   row,col,utmx,utmy = pxls[i]
#   predata.append([utmx, utmy, pred_data[i][0]*(-10)])

# # Specify the file name
# filename = 'DATA.csv'

# # Write to CSV file with a heading
# with open(filename, mode='w', newline='') as file:
#     writer = csv.writer(file)

#     # Write the heading
#     writer.writerow(['UTMx', 'UTMy', 'Subsidence'])

#     # Write the data
#     writer.writerows(predata)

# print(f'Data written to {filename} with a heading.')

data[0][0]

output_path = 'predicted_map.tif'  # output file
filename = 'processed_count.csv'
batch_size = 60000
num_samples = len(pxls)

predicted_map = aspect_normalized.copy()  # or np.zeros_like(ndvi_normalized)
# Update profile for the output file
profile.update({
    'dtype': predicted_map.dtype,
    'count': 1,
    # 'compress': 'lzw'  # optional: compress output

})

# Step 1: Determine how many rows are already processed
processed_count = 0
if os.path.exists(filename):
    with open(filename, 'r') as f:
        reader = csv.reader(f)
        processed_count = sum(1 for row in reader) - 1  # subtract header

# Step 2: Write header if new file
if processed_count == 0:
    with open(filename, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['x', 'y','utmx', 'utmy' ,'predicted_value'])  # adjust columns as needed

# Step 3: Batch processing
for batch_start in range(processed_count, num_samples, batch_size):

    batch_end = min(batch_start + batch_size, num_samples)
    current_batch_size = batch_end - batch_start


    # Initialize batch arrays
    data_ndvi      = np.zeros([current_batch_size,30,30],dtype='float32')
    data_dist      = np.zeros([current_batch_size,30,30],dtype='float32')
    data_elevation = np.zeros([current_batch_size,30,30],dtype='float32')
    data_twi       = np.zeros([current_batch_size,30,30],dtype='float32')
    data_slope     = np.zeros([current_batch_size,30,30],dtype='float32')
    data_landuse   = np.zeros([current_batch_size,30,30],dtype='float32')
    data_spi       = np.zeros([current_batch_size,30,30],dtype='float32')
    data_aspect    = np.zeros([current_batch_size,30,30],dtype='float32')
    data_water     = np.zeros([current_batch_size,30,30],dtype='float32')

    coords = []

    for c in range(current_batch_size):
      idx = batch_start + c

      x, y, utmx, utmy = pxls[idx]
      coords.append((x, y,utmx, utmy))

      # Extract 30x30 patches
      data_ndvi[c]      = ndvi_normalized[x-15:x+15, y-15:y+15]
      data_dist[c]      = dist_normalized[x-15:x+15, y-15:y+15]
      data_elevation[c] = elevation_normalized[x-15:x+15, y-15:y+15]
      data_twi[c]       = twi_normalized[x-15:x+15, y-15:y+15]
      data_slope[c]     = slope_normalized[x-15:x+15, y-15:y+15]
      data_landuse[c]   = landuse_normalized[x-15:x+15, y-15:y+15]
      data_spi[c]       = spi_normalized[x-15:x+15, y-15:y+15]
      data_aspect[c]    = aspect_normalized[x-15:x+15, y-15:y+15]
      data_water[c]     = water_normalized[x-15:x+15, y-15:y+15]

    features =[data_dist,data_elevation,data_ndvi, data_slope,
                data_landuse, data_twi,data_spi,data_aspect,data_water]

    # Stack along a new axis (9, batch_size, 30, 30) -> then move axes to (batch_size, 9, 30, 30)
    Data = np.stack(features, axis=1) # shape: (batch_size, 9, 30, 30)

    # Data = Data.transpose(0, 2, 3, 1)   # shape: (batch_size, 30, 30, 9)
    Data = Data.reshape(current_batch_size, 30, 30, 9)
    # Predict
    pred_data = model.predict(Data)  # assuming output shape = (batch_size, 1)

    # Save predictions and update predicted_map
    with open(filename, 'a', newline='') as f:
        writer = csv.writer(f)
        for i, (x, y,utmx, utmy) in enumerate(coords):
            val = pred_data[i][0] * (-10)   # scalar prediction
            predicted_map[x, y] = val
            writer.writerow([x, y,utmx, utmy, val])
    # Release batch memory
    del data_ndvi, data_dist, data_elevation, data_twi, data_slope
    del data_landuse, data_spi, data_aspect, data_water, Data, pred_data
    import gc
    gc.collect()
    # Save current predicted_map as GeoTIFF after each batch
    with rio.open(output_path, 'w', **profile) as dst:
        dst.write(predicted_map, 1)

    print(f"Processed and saved batch {batch_start} to {batch_end} and updated GeoTIFF.")

Data[0][0]

# # Prepare rows to write
    # rows_to_write = []
    # for i in range(current_batch_size):
    #     px, py, utmx, utmy = pxls[batch_start + i]
    #     prediction_value = pred_data[i][0] * (-10)
    #     rows_to_write.append([px, py, utmx, utmy, prediction_value])

    # # Append results
    # with open(filename, mode='a', newline='') as file:
    #     writer = csv.writer(file)
    #     writer.writerows(rows_to_write)

# import numpy as np
# import rasterio
# from rasterio.windows import Window
# from sklearn.preprocessing import MinMaxScaler
# import tensorflow as tf
# import cv2
# import csv

# #  Define rasters
# normalized_rasters = {
#     "ndvi": ndvi_normalized, "dist": dist_normalized, "elevation": elevation_normalized,
#     "slope": slope_normalized, "twi": twi_normalized, "landuse": landuse_normalized,
#     "spi": spi_normalized, "aspect": aspect_normalized, "water": water_normalized
# }
# # Assume raster height and width
# height, width = normalized_rasters["ndvi"].shape
# # Sliding window parameters
# patch_size = 30
# half_size = patch_size // 2
# batch_size = 128
# tile_height = 1000
# tile_width = 1000
# step = 30
# # Initialize output array with zeros or NaNs (to store predicted values)
# predicted_map = np.zeros((height, width))
# for row in range(15,500 ):
#     for col in range(15,500):


#         # Extract 30x30 patches from each normalized raster
#         patch = np.stack([
#             normalized_rasters["ndvi"][row - half_size:row + half_size, col - half_size:col + half_size],
#             normalized_rasters["dist"][row - half_size:row + half_size, col - half_size:col + half_size],
#             normalized_rasters["elevation"][row - half_size:row + half_size, col - half_size:col + half_size],
#             normalized_rasters["slope"][row - half_size:row + half_size, col - half_size:col + half_size],
#             normalized_rasters["twi"][row - half_size:row + half_size, col - half_size:col + half_size],
#             normalized_rasters["landuse"][row - half_size:row + half_size, col - half_size:col + half_size],
#             normalized_rasters["spi"][row - half_size:row + half_size, col - half_size:col + half_size],
#             normalized_rasters["aspect"][row - half_size:row + half_size, col - half_size:col + half_size],
#             normalized_rasters["water"][row - half_size:row + half_size, col - half_size:col + half_size]
#         ], axis=-1)  # Shape: (30, 30, 9)
#         patch = np.array(patch).reshape(1, 30, 30, 9)
#         predict_pxl = model.predict(patch, verbose=0)[0][0]*(-10)
#         # Set the predicted value to all pixels in the patch
#         predicted_map[row,col] = predict_pxl

# import rasterio

# # Example: get metadata from one of your input rasters
# with rasterio.open("NDVI_aligned.tif") as src:
#     meta = src.meta.copy()

# # Update metadata for the output
# meta.update(dtype=rasterio.float32, count=1)

# # Save predicted_map as GeoTIFF
# output_path = "predicted_map.tif"
# with rasterio.open(output_path, 'w', **meta) as dst:
#     dst.write(predicted_map.astype(rasterio.float32), 1)