# -*- coding: utf-8 -*-
"""Subsidence_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152sK2OWG5nfRbqH_LZtagoOTXVUV2pdc
"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/gdrive')
# %cd gdrive/My\Drive/Mythesis

!pip install pandas

!pip install xlrd==2.0.1

!pip install pyproj

!pip install rasterio

!pip install plot_model

!pip install livelossplot

# Required libraries

import numpy as np
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from scipy import stats
import pandas as pd
import  pyproj
import rasterio as rio
import numpy as np
from sklearn.model_selection import train_test_split
import csv
import tensorflow as tf
from tensorflow import keras as ks
from keras.models import Sequential
from tensorflow.keras.optimizers import Adam, SGD, Adadelta
from keras.regularizers import l2 , l1
from keras import regularizers
from sklearn.model_selection import train_test_split
from keras.layers import Dense, Conv2D, Flatten, BatchNormalization, Activation, MaxPooling2D, Dropout, AveragePooling2D, GlobalMaxPooling2D
import livelossplot
import keras
import tensorflow as tf
import matplotlib.pyplot as plt
import os
import json
from tensorflow.keras.callbacks import ModelCheckpoint, LambdaCallback
from tensorflow.keras.models import load_model
from sklearn.preprocessing import MinMaxScaler
import cv2

# load PSs
df = pd.read_excel('PSnoup.xls')
print (df)
ydata=df['CUMUL_DISP']

p = pyproj.Proj(proj='utm', zone=39, ellps='WGS84')

lat=df['LAT']
lon=df['LON']

lat=list(lat)
lon=list(lon)

utmx, utmy = p(lon,lat)



print('min of CUMUL_DISP:', min(ydata), 'mm')
print('max of CUMUL_DISP:', max(ydata), 'mm')

ndvi_1     =rio.open('NDVI.tif')
dist_1     =rio.open('distwells.tif')
elevation_1=rio.open('Elevation.tif')
twi_1      =rio.open('TWI.tif')
spi_1      =rio.open('SPI.tif')
slope_1    =rio.open('slope.tif')
landuse_1  =rio.open('landuse.tif')
w_1  =rio.open('watertable.tif')
a_1  =rio.open('aspect.tif')

ndvi_1 .shape

print(w_1.shape,a_1.shape,spi_1.shape,ndvi_1 .shape,dist_1.shape,elevation_1.shape,landuse_1.shape,slope_1.shape,twi_1.shape,w_1.shape)

#find row and column of PSs


pxyn=[]
pxyd=[]
pxye=[]
pxyt=[]
pxys=[]
pxyl=[]
pxyspi=[]
pxyw=[]
pxya=[]

for i in range(len(utmx)):
    rown,coln=ndvi_1.index(utmx[i],utmy[i])
    rowl,coll=landuse_1.index(utmx[i],utmy[i])
    rowd,cold=dist_1.index(utmx[i],utmy[i])
    rowe,cole=elevation_1.index(utmx[i],utmy[i])
    rowt,colt=twi_1.index(utmx[i],utmy[i])
    rows,cols=slope_1.index(utmx[i],utmy[i])
    rowa,cola=a_1.index(utmx[i],utmy[i])
    roww,colw=w_1.index(utmx[i],utmy[i])
    rowspi,colspi=spi_1.index(utmx[i],utmy[i])

    if 15<rown<3028 and 15<coln<3149 and 15<rowd<3028 and 15<cold<3149 and 15<rowt<3028 and 15<colt<3149 and 15<rowe<3028 and 15<cole<3149 and  15<rows<3028 and 15<cols<3149 and  15<rowl<3028 and 15<coll<3149   and  15<roww<3028 and 15<colw<3149   and  15<rowa<3028 and 15<cola<3149   and  15<rowspi<3028 and 15<colspi<3149:
        pxyn.append([rown,coln,i])
        pxyd.append([rowd,cold,i])
        pxye.append([rowe,cole,i])
        pxyt.append([rowt,colt,i])
        pxys.append([rows,cols,i])
        pxyl.append([rowl,coll,i])
        pxyw.append([roww,colw,i])
        pxyspi.append([rowspi,colspi,i])
        pxya.append([rowa,cola,i])

#Check len of each pxys


len(pxyn),len(pxyd),len(pxye),len(pxyt),len(pxys),len(pxyl),len(pxyw),len(pxya),len(pxyspi)

ndvi_2      = ndvi_1.read(1)
dist_2      = dist_1.read(1)
elevation_2 = elevation_1.read(1)
twi_2       = twi_1.read(1)
spi_2       = spi_1.read(1)
slope_2     = slope_1.read(1)
landuse_2   = landuse_1.read(1)
water_2     = w_1.read(1)
aspect_2    = a_1.read(1)

def read_img(img_path):
  with rasterio.open('MyRasterImage.tif') as src:
    w = src.read(1, window=Window(0, 0, 3043, 3164))

print(w.shape)

aspect_2.shape



ndvi_2      = ndvi_1.read(1)
dist_2      = dist_1.read(1)
elevation_2 = elevation_1.read(1)
twi_2       = twi_1.read(1)
spi_2       = spi_1.read(1)
slope_2     = slope_1.read(1)
landuse_2   = landuse_1.read(1)
water_2     = w_1.read(1)
aspect_2    = a_1.read(1)
target_width, target_height = 3043,3164


# Resize using nearest-neighbor interpolation (preserves original values)
ndvi_resized = cv2.resize(ndvi_2, (target_height,target_width), interpolation=cv2.INTER_NEAREST)
dist_resized = cv2.resize(ndvi_2, (target_height,target_width), interpolation=cv2.INTER_NEAREST)
spi_resized = cv2.resize(ndvi_2, (target_height,target_width), interpolation=cv2.INTER_NEAREST)
twi_resized = cv2.resize(ndvi_2, (target_height,target_width), interpolation=cv2.INTER_NEAREST)
landuse_resized = cv2.resize(ndvi_2, (target_height,target_width), interpolation=cv2.INTER_NEAREST)
slope_resized = cv2.resize(ndvi_2, (target_height,target_width), interpolation=cv2.INTER_NEAREST)
aspect_resized = cv2.resize(ndvi_2,(target_height,target_width), interpolation=cv2.INTER_NEAREST)
water_resized = cv2.resize(ndvi_2, (target_height,target_width), interpolation=cv2.INTER_NEAREST)
elevation_resized = cv2.resize(ndvi_2,(target_height,target_width), interpolation=cv2.INTER_NEAREST)

# normalize data



scaler = MinMaxScaler(feature_range=(0,1))

scaler.fit(ndvi_resized)
ndvi_normalized      = scaler.transform(ndvi_resized)

scaler.fit(dist_resized)
dist_normalized      = scaler.transform(dist_resized)


scaler.fit(elevation_resized)
elevation_normalized = scaler.transform(elevation_resized)

scaler.fit(twi_resized)
twi_normalized       = scaler.transform(twi_resized)

scaler.fit(slope_resized)
slope_normalized     = scaler.transform(slope_resized)

scaler.fit(landuse_resized)
landuse_normalized   = scaler.transform(landuse_resized)

scaler.fit(spi_resized)
spi_normalized      = scaler.transform(spi_resized)

scaler.fit(water_resized)
water_normalized      = scaler.transform(water_resized)

scaler.fit(aspect_resized)
aspect_normalized      = scaler.transform(aspect_resized)

dist_normalized.shape,aspect_normalized.shape,water_normalized.shape,twi_normalized.shape,spi_normalized.shape,ndvi_normalized.shape,landuse_normalized.shape

# create 30*30 windows over each common point in all 6 features

u_in_all=[]
for i in range(len(pxyn)):
  u_in_all.append(pxyn[i][2])

ydata_=[] # common subsidence

utmx2=[]
utmy2=[]
for i in u_in_all:
    ydata_.append(ydata[i])
    utmx2.append(utmx[i])
    utmy2.append(utmy[i])

ydata_ = np.array(ydata_)
ydata_ = ydata_.astype(np.float32)

utmy2 = np.array(utmy2)
utmx2 = np.array(utmx2)
utmy2 =utmy2.astype(np.float32)
utmx2 = utmx2.astype(np.float32)

ydata2 = abs(ydata_)/10




data_ndvi      = np.zeros([len(u_in_all),30,30],dtype='float32')
data_dist      = np.zeros([len(u_in_all),30,30],dtype='float32')
data_elevation = np.zeros([len(u_in_all),30,30],dtype='float32')
data_twi       = np.zeros([len(u_in_all),30,30],dtype='float32')
data_slope     = np.zeros([len(u_in_all),30,30],dtype='float32')
data_landuse   = np.zeros([len(u_in_all),30,30],dtype='float32')
data_spi       = np.zeros([len(u_in_all),30,30],dtype='float32')
data_aspect    = np.zeros([len(u_in_all),30,30],dtype='float32')
data_water     = np.zeros([len(u_in_all),30,30],dtype='float32')

np.save('ydata2.npy',ydata2)
np.save('utmx2.npy',utmx2)
np.save('utmy2.npy',utmy2)



#elevation slope twi
c=0

for i in range(len(pxyl)):


    ndvi_w      = ndvi_normalized     [pxyn[i][0]-15:pxyn[i][0]+15      , pxyn[i][1]-15:pxyn[i][1]+15]
    dist_w      = dist_normalized     [pxyd[i][0]-15:pxyd[i][0]+15      , pxyd[i][1]-15:pxyd[i][1]+15]
    elevation_w = elevation_normalized[pxye[i][0]-15:pxye[i][0]+15      , pxye[i][1]-15:pxye[i][1]+15]
    slope_w     = slope_normalized    [pxys[i][0]-15:pxys[i][0]+15      , pxys[i][1]-15:pxys[i][1]+15]
    twi_w       = twi_normalized      [pxyt[i][0]-15:pxyt[i][0]+15      , pxyt[i][1]-15:pxyt[i][1]+15]
    landuse_w   = landuse_normalized  [pxyl[i][0]-15:pxyl[i][0]+15      , pxyl[i][1]-15:pxyl[i][1]+15]
    spi_w       = spi_normalized      [pxyspi[i][0]-15:pxyspi[i][0]+15  , pxyspi[i][1]-15:pxyspi[i][1]+15]
    water_w     = water_normalized    [pxyw[i][0]-15:pxyw[i][0]+15      , pxyw[i][1]-15:pxyw[i][1]+15]
    aspect_w    = aspect_normalized   [pxya[i][0]-15:pxya[i][0]+15      , pxya[i][1]-15:pxya[i][1]+15]

    data_ndvi[c]     = ndvi_w
    data_dist[c]     = dist_w
    data_elevation[c]= elevation_w
    data_twi[c]      = twi_w
    data_slope[c]    = slope_w
    data_landuse[c]  = landuse_w
    data_spi[c]      = spi_w
    data_water[c]    = water_w
    data_aspect[c]   = aspect_w
    c=c+1

# Create 3D input matrix [ 30 row *30 column *6 channel]
# remember that we have 47209 sample

Data=np.zeros([len(u_in_all),9,30,30])# sample:len(u_in_all), channels(features):9, row:30, column:30



for i in range(len(u_in_all)):
    Data[i,0:9,:,:]=[data_dist[i],data_elevation[i],data_ndvi[i], data_slope[i], data_landuse[i], data_twi[i],data_spi[i],data_aspect[i],data_water[i]]

np.save('data.npy',Data)
np.save('ydata.npy',ydata2)
np.save('utmx2.npy',utmx2)
np.save('utmy2.npy',utmy2)

Data=np.load('data.npy')

ydata2=np.load('ydata2.npy')
utmx2=np.load('utmx2.npy')
utmy2=np.load('utmy2.npy')
len_u_in_all=60126

#split train and test


indices = np.arange(len_u_in_all)

x_train, x_test, y_train, y_test ,indices_train, indices_test = train_test_split(Data, ydata2,indices, test_size=0.1, shuffle=True)

#split validation data
trainshape=x_train.shape
indices2 = np.arange(trainshape[0])
x_train2, x_val, y_train2, y_val  ,indices_train2, indices_val = train_test_split(x_train, y_train, indices2, test_size=0.1, shuffle=True)

x_train2 = x_train2.reshape((x_train2.shape[0],30,30,9))
x_test   = x_test.reshape((x_test.shape[0],30,30,9))
x_val    = x_val.reshape((x_val.shape[0],30,30,9))

np.save('ind_train2.npy',indices_train2)
np.save('ind_test.npy',indices_test)
np.save('ind_val.npy',indices_val)

np.save('x_train2.npy',x_train2)

np.save('x_test.npy',x_test)

np.save('x_val.npy',x_val)

np.save('y_train2.npy',y_train2)
np.save('y_test.npy',y_test)
np.save('y_val.npy',y_val)

# Create lists for utmx and utmy for training data
utmx_train = [utmx2[i] for i in indices_train2]
utmy_train = [utmy2[i] for i in indices_train2]
# y_train_real = [ydata3[i] for i in ind_train2]
# Create lists for utmx and utmy for testing data
utmx_test = [utmx2[i] for i in indices_test]
utmy_test = [utmy2[i] for i in indices_test]
# y_test_real = [ydata3[i] for i in ind_test]

np.save('utmx_train',utmx_train)
np.save('utmy_train',utmy_train)
np.save('utmx_test',utmx_test)
np.save('utmy_test',utmy_test)

x_train2=np.load('x_train2.npy')
x_test=np.load('x_test.npy')
x_val=np.load('x_val.npy')
y_train2=np.load('y_train2.npy')
y_test=np.load('y_test.npy')
y_val=np.load('y_val.npy')

x_train2=np.load('x_train2.npy')
print(x_train2.shape)

# ind_train2=np.load('ind_train2.npy')
# ind_test=np.load('ind_test.npy')
# ind_val=np.load('ind_val.npy')

#1401.04.19
#define the convolutional neural network architecture

model = Sequential()
model.add(Conv2D(32, (1,1), padding="same" ,input_shape=(30,30,9), activation="relu"))
model.add(Conv2D(32, (3,3), padding="same", activation="relu"))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.1))

model.add(Conv2D(32, (1,1), padding="same" ,input_shape=(30,30,6), activation="relu"))
model.add(Conv2D(32, (3,3), padding="same", activation="relu"))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.1))

model.add(Conv2D(1024, (1,1), padding="same" ,input_shape=(30,30,6), activation="relu"))

model.add(Conv2D(1024, (3,3), padding="same", activation="relu"))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.1))

model.add(Flatten())

model.add(Dense(1024, activation="relu")) # 1024
model.add(BatchNormalization())
model.add(Dropout(0.1))


model.add(Dense(1024, activation="relu")) # 1024
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Dense(512, activation="relu")) # 512
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Dense(512, activation="relu")) # 512
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Dense(256, activation="relu")) # 256
model.add(BatchNormalization())




model.add(Dense(1,activation='linear'))

model.summary()

plot_losses = livelossplot.PlotLossesKeras()

#model compile

model.compile(loss='mse' , optimizer= Adam(learning_rate=0.0001),metrics =['mae'])
checkpoint = ModelCheckpoint ('Bestmodel.h5',
                              save_best_only = True,
                              monitor = 'val_loss',
                              verbose =1)


# Train the model with the checkpoint callback
history = model.fit(x_train2, y_train2,
                    batch_size=128,
                    epochs=150,
                    callbacks= [plot_losses,checkpoint],
                    verbose=1,
                    validation_data=(x_val, y_val),
                    shuffle=True)

# Train the model with the checkpoint callback
history = model.fit(x_train2, y_train2,
                    batch_size=128,
                    epochs=150,
                    callbacks= [plot_losses,checkpoint],
                    verbose=1,
                    validation_data=(x_val, y_val),
                    shuffle=True)

import os
from keras.models import load_model
from keras import metrics

model_path = 'Bestmodel.h5'  # Update this to the correct path if needed

# Check if the file exists before loading
if os.path.exists(model_path):
    # Define custom objects
    custom_objects = {
        'mse': metrics.mean_squared_error,  # Add other custom objects if necessary
    }

    # Load the model with custom objects
    model = load_model(model_path, custom_objects=custom_objects)
    print("Model loaded successfully.")
else:
    print(f"The file {model_path} does not exist.")

# from keras.models import load_model

# # identical to the previous one
# model = load_model('my_model.h5')dict_keys(['loss', 'val_loss'])

# Evaluate the model on training data
loss = model.evaluate(x_train2, y_train2)

# Extract the loss value (assuming it's the first element)
train_loss = loss[0]  # Get the first element for loss
print('Train Loss: {}'.format(round(float(train_loss), 2)))

# Evaluate on validation data
val_loss = model.evaluate(x_val, y_val)
val_loss_value = val_loss[0]  # Get the first element for validation loss
print('Validation Loss: {}'.format(round(float(val_loss_value), 2)))

# Evaluate on test data
test_loss = model.evaluate(x_test, y_test)
test_loss_value = test_loss[0]  # Get the first element for test loss
print('Test Loss: {}'.format(round(float(test_loss_value), 2)))

!pip install opencv-python

import numpy as np
import rasterio
from rasterio.windows import Window
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf
import cv2

# 🔹 Define rasters
rasters = {
    "ndvi": ndvi_normalized, "dist": dist_normalized, "elevation": elevation_normalized,
    "slope": slope_normalized, "twi": twi_normalized, "landuse": landuse_normalized,
    "spi": spi_normalized, "aspect": aspect_normalized, "water": water_normalized
}

with rasterio.open('NDVI.tif') as src:
    meta = src.meta.copy()
    meta.update({
        'driver': 'GTiff',
        'dtype': 'float32',
        'count': 1,  # Single band output
        'nodata': None  # Define no data value if applicable
    })

# ✅ Image dimensions
height, width = rasters["water"].shape  # Example shape: (3043, 3164)

# ✅ Define sliding window parameters
patch_size = 30
half_size = patch_size // 2
batch_size = 128  # ⚡️ Increase for faster GPU processing

# ✅ Create output array (same size as input)
predictions = np.zeros((height, width), dtype=np.float32)

# ✅ Process image in batches to utilize GPU
patches = []
positions = []

# Write the predictions to a new GeoTIFF
with rasterio.open('predictions.tif', 'w', **meta) as dst:
    for row in range(half_size, height - half_size):
        for col in range(half_size, width - half_size):
            # Extract a 30x30 patch from each raster
            patch = np.stack([
                rasters["ndvi"][row - half_size:row + half_size, col - half_size:col + half_size],
                rasters["dist"][row - half_size:row + half_size, col - half_size:col + half_size],
                rasters["elevation"][row - half_size:row + half_size, col - half_size:col + half_size],
                rasters["slope"][row - half_size:row + half_size, col - half_size:col + half_size],
                rasters["twi"][row - half_size:row + half_size, col - half_size:col + half_size],
                rasters["landuse"][row - half_size:row + half_size, col - half_size:col + half_size],
                rasters["spi"][row - half_size:row + half_size, col - half_size:col + half_size],
                rasters["aspect"][row - half_size:row + half_size, col - half_size:col + half_size],
                rasters["water"][row - half_size:row + half_size, col - half_size:col + half_size]
            ], axis=-1)  # Shape: (30, 30, 9)


            batch_patch = patch.reshape(1, 30, 30, 9)

            predict_pxl= model.predict(batch_patch, verbose=0)  # ⚡️ Fast GPU inference

            predictions[row, col] = (predict_pxl.item()) * -10

                # Write predictions to the output file after processing the batch
            # print(f"Predictions for row {row}, col {col}: {predictions[row,col]}")


            dst.write(predictions[row:row+1, col:col+1], 1)
            # print(f"Writing prediction {predictions[row, col]} to position ({row}, {col}) in the output file.")
        print(f"✅ Processed row {(row,col)}/{height}")

print("🎉 Processing complete! Saved as 'predictions.tif'")

import numpy as np
import rasterio
from rasterio.transform import from_origin
from rasterio.crs import CRS
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
import os
import time
from datetime import datetime

# 🔹 Load a reference raster to get metadata
reference_raster_path = "watertable.tif"  # Update to an actual file path
with rasterio.open(reference_raster_path) as ref:
    ref_meta = ref.meta.copy()
    crs = ref.crs
    transform = ref.transform
    nodata_value = ref.nodata

# 🔹 Define rasters (example)
rasters = {
    "ndvi": ndvi_normalized, "dist": dist_normalized, "elevation": elevation_normalized,
    "slope": slope_normalized, "twi": twi_normalized, "landuse": landuse_normalized,
    "spi": spi_normalized, "aspect": aspect_normalized, "water": water_normalized
}



# ✅ Image dimensions
height, width = rasters["water"].shape

# ✅ Define sliding window parameters
patch_size = 30
half_size = patch_size // 2
batch_size = 128  # ⚡ Increase for faster GPU processing

# ✅ Create output array (same size as input)
predictions = np.full((height, width), nodata_value, dtype=np.float32)  # Use nodata value

# ✅ Checkpoint directory
checkpoint_dir = 'checkpoints'
if not os.path.exists(checkpoint_dir):
    os.makedirs(checkpoint_dir)

def save_checkpoint(predictions, part_number):
    filename = os.path.join(checkpoint_dir, f'predictions_part{part_number}.tif')
    with rasterio.open(filename, 'w', **ref_meta) as dst:
        dst.write(predictions, 1)
    print(f"Checkpoint saved as {filename}")

# ✅ Load previous checkpoint if exists
def load_checkpoint():
    checkpoint_files = sorted(
        [f for f in os.listdir(checkpoint_dir) if f.endswith(".tif")],
        key=lambda x: os.path.getmtime(os.path.join(checkpoint_dir, x))
    )
    latest_checkpoint = checkpoint_files[-1] if checkpoint_files else None
    if latest_checkpoint:
        print(f"Resuming from checkpoint: {latest_checkpoint}")
        with rasterio.open(os.path.join(checkpoint_dir, latest_checkpoint)) as src:
            return src.read(1)
    return np.full((height, width), nodata_value, dtype=np.float32)  # Start fresh if no checkpoint

# ✅ Initial predictions (from previous checkpoint or starting fresh)
predictions = load_checkpoint()

# ✅ Process patches
patches = []
positions = []

for row in range(half_size, height - half_size):
    for col in range(half_size, width - half_size):
        # Extract 30x30 patch from each raster
        patch = np.stack([
            rasters["ndvi"][row - half_size:row + half_size, col - half_size:col + half_size],
            rasters["dist"][row - half_size:row + half_size, col - half_size:col + half_size],
            rasters["elevation"][row - half_size:row + half_size, col - half_size:col + half_size],
            rasters["slope"][row - half_size:row + half_size, col - half_size:col + half_size],
            rasters["twi"][row - half_size:row + half_size, col - half_size:col + half_size],
            rasters["landuse"][row - half_size:row + half_size, col - half_size:col + half_size],
            rasters["spi"][row - half_size:row + half_size, col - half_size:col + half_size],
            rasters["aspect"][row - half_size:row + half_size, col - half_size:col + half_size],
            rasters["water"][row - half_size:row + half_size, col - half_size:col + half_size]
        ], axis=-1)  # Shape: (30, 30, 9)

        patches.append(patch)
        positions.append((row, col))

        # Process batch when full
        if len(patches) >= batch_size:
            batch = np.array(patches).reshape(-1, 30, 30, 9)
            batch_predictions = model.predict(batch, verbose=0)  # ⚡ Fast GPU inference

            # Save predictions to the output array
            for i, (r, c) in enumerate(positions):
                predictions[r, c] = (batch_predictions[i].item())*-10

            # Save checkpoint
            save_checkpoint(predictions, row // 100)

            # Reset batch
            patches, positions = [], []

    print(f"✅ Processed row {row}/{height}")

# ✅ Handle remaining patches
if patches:
    batch = np.array(patches).reshape(-1, 30, 30, 9)
    batch_predictions = model.predict(batch, verbose=0)
    for i, (r, c) in enumerate(positions):
        predictions[r, c] = (batch_predictions[i].item())*-10

# ✅ Save final GeoTIFF output with metadata
output_file = 'predictions_final.tif'
ref_meta.update(dtype=rasterio.float32, count=1, compress='lzw')

with rasterio.open(output_file, 'w', **ref_meta) as dst:
    dst.write(predictions, 1)

print(f"🎉 Processing complete! Saved as {output_file}")

data = Data.reshape((Data.shape[0],30,30,9))

batch_size = 32  # Adjust based on available memory
num_samples = 60126

predictions = []

for i in range(0, num_samples, batch_size):
    batch = data[i:i + batch_size]  # Slice the batch
    batch_pred = model.predict(batch)    # Predict the batch
    predictions.append(batch_pred)       # Store results

predictions = np.concatenate(predictions, axis=0)  # Concatenate all predictions

print(pxyn[0])

predictions[0]



# Open the original NDVI image to get geotransform
ndvi_1     =rio.open('NDVI.tif')
with rasterio.open("NDVI.tif") as src:
    ndvi = src.read()
    transform = src.transform
    crs = src.crs

#find row and column of PSs
rows, cols = ndvi.shape [1], ndvi.shape[2]  # Adjust based on your area

pxyn=[]
image_pred = np.zeros((rows, cols), dtype=np.float32)

# len(utmx2)
for i in range(len(utmx2)):
    row,col=ndvi_1.index(utmx2[i],utmy2[i])
    # print(predictions[i],row,col,image_pred[row - 15 : row + 15, col - 15 : col + 15].shape)
    image_pred[(row - 15) : row + 15, col - 15 : col + 15] = predictions[i]


    # print(np.unique(image_pred))
# Create the GeoTIFF file
with rasterio.open(
    "image_pred.tif",
    "w",
    driver="GTiff",
    height=image_pred.shape[0],
    width=image_pred.shape[1],
    count=1,
    dtype=np.float32,
    crs=crs,
    transform=transform,
) as dst:
    dst.write(image_pred, 1)

print("GeoTIFF created successfully: image_pred.tif")

print(np.unique(image_pred),image_pred.shape)

row - 15 : row + 15

print(ndvi.shape)

import numpy as np
import rasterio
from rasterio.transform import from_origin

# Open the original NDVI image to get geotransform
with rasterio.open("NDVI.tif") as src:
    ndvi = src.read()
    transform = src.transform
    crs = src.crs
print(ndvi.shape)

# Define the output dimensions
rows, cols = ndvi.shape [0], ndvi.shape[1]  # Adjust based on your area
block_size = 30
image_pred = np.zeros((rows, cols), dtype=np.float32)

# Iterate over the stored pxyn indices
for idx, (row, col, i) in enumerate(pxyn):
    print(row,col,i,idx)


    if 15 < row < rows - 15 and 15 < col < cols - 15:
        print(predictions[i][0] )
        image_pred[row - 15 : row + 15, col - 15 : col + 15] = predictions[i][0]


# Create the GeoTIFF file
with rasterio.open(
    "image_pred.tif",
    "w",
    driver="GTiff",
    height=image_pred.shape[0],
    width=image_pred.shape[1],
    count=1,
    dtype=np.float32,
    crs=crs,
    transform=transform,
) as dst:
    dst.write(image_pred, 1)

print("GeoTIFF created successfully: image_pred.tif")

# load PSs
df = pd.read_csv('output.csv')
print (df)
predictions=df['predicted subsidence']

np.unique(image_pred)

np.min(predictions*-10), np.max(predictions*-10),len(predictions)

import csv


# Prepare the predata list
predata = []
for i in range(len(utmx2)):
    predata.append([utmx2[i], utmy2[i], ydata2[i] * (-10),predictions[i][0]*(-10)])

# Specify the file name
filename = 'output.csv'

# Write to CSV file with a heading
with open(filename, mode='w', newline='') as file:
    writer = csv.writer(file)

    # Write the heading
    writer.writerow(['UTMx', 'UTMy', 'Subsidence','predicted subsidence'])

    # Write the data
    writer.writerows(predata)

print(f'Data written to {filename} with a heading.')



model.evaluate(data, ydata2)

pred_data=model.predict(data)

pred_train=model.predict(x_train2)
pred_test=model.predict(x_test)

utmx_train=np.load('utmx_train.npy')
utmy_train=np.load('utmy_train.npy')
y_train_real=np.load('y_train_real.npy')

utmx_test=np.load('utmx_test.npy')
utmy_test=np.load('utmx_test.npy')
y_test_real=np.load('y_test_real.npy')

scaler = MinMaxScaler()
scaler.fit(y_train_real)
pred_train_real = scaler.inverse_transform(pred_train)
mse = mean_squared_error(y_train_real, pred_train_real)
mse

pretrain=[]
for i in range(len(pred_train)):
  pretrain.append([utmx_train[i],utmy_train[i],pred_train[i][0]*(-10),y_train2[i]*(-10)])


pretest=[]
for i in range(len(pred_test)):
  pretest.append([utmx_test[i],utmy_test[i],pred_test[i][0]*(-10),y_test[i]*(-10)])

header = ['utmX','utmY','Prediction','Ground truth']
with open('pstrain.csv', 'w') as f:

    # using csv.writer method from CSV package
    write = csv.writer(f)
    write.writerow(header)
    write.writerows(pretrain)

with open('pstest.csv', 'w') as f:

    # using csv.writer method from CSV package
    write = csv.writer(f)
    write.writerow(header)
    write.writerows(pretest)

tf.keras.utils.plot_model(model, to_file='mymodel.pdf')

"""# **Comparison between CNN and Traditional interpolation methods**





"""

# load PSs
dftrain = pd.read_csv('pstrain.csv')

pred_train=dftrain['Prediction']

dftest = pd.read_csv('pstest.csv')

pred_test=dftest['Prediction']

# # IDW
# df_train_I = pd.read_excel('IDW_train.xls')
# df_test_I  = pd.read_excel('IDW_test.xls')

# IDW_train = df_train_I['IDW']
# IDW_test  = df_test_I ['IDW']

# # RBF
# df_train_R = pd.read_excel('RBF_train.xls')
# df_test_R  = pd.read_excel('RBF_test.xls')

# RBF_train = df_train_I['RBF']
# RBF_test  = df_test_I ['RBF']

# #Kriging
# df_train_K = pd.read_excel('Kriging_train.xls')
# df_test_K  = pd.read_excel('Kriging_test.xls')

# kriging_train = df_train_I['kriging']
# kriging_test  = df_test_I ['krifing']

"""# **Root Mean Squared Error (RMSE)**"""

# Function to calculate Root Mean Squared Error (RMSE)
def calculate_rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))
#_____________________________________ model RMSE__________________________________

# Assuming you have y_train_true, y_train_pred, y_test_true, y_test_pred loaded

# Calculate RMSE for training set
rmse_train = calculate_rmse(y_train2 , pred_train)

# Calculate RMSE for test set
rmse_test = calculate_rmse(y_test , pred_test)

print(f"Model RMSE for training set: {rmse_train}")
print(f"Model RMSE for test set: {rmse_test}")
# #_____________________________________ IDW RMSE__________________________________

# # Calculate RMSE for training set
# rmse_trainI = calculate_rmse(y_train2 - IDW_train)

# # Calculate RMSE for test set
# rmse_testI  = calculate_rmse(y_test - IDW_test)

# print(f"Model RMSE for training set: {rmse_trainI}")
# print(f"Model RMSE for test set: {rmse_testI}")


# #_____________________________________ RBF RMSE__________________________________

# # Calculate RMSE for training set
# rmse_trainR = calculate_rmse(y_train2 - RBF_train)

# # Calculate RMSE for test set
# rmse_testR  = calculate_rmse(y_test - RBF_test)

# print(f"Model RMSE for training set: {rmse_trainR}")
# print(f"Model RMSE for test set: {rmse_testR}")


# #_____________________________________ Kriging RMSE__________________________________


# # Calculate RMSE for training set
# rmse_trainK = calculate_rmse(y_train2 - kriging_train)

# # Calculate RMSE for test set
# rmse_testK  = calculate_rmse(y_test - kriging_test)

# print(f"Model RMSE for training set: {rmse_trainK}")
# print(f"Model RMSE for test set: {rmse_testK}")

"""# **R-squared (R2 score)**"""

# Function to calculate R-squared
def calculate_R2(y_true, y_pred):
    return r2_score(y_true, y_pred)
#_____________________________________ model R2__________________________________

# Assuming you have y_train_true, y_train_pred, y_test_true, y_test_pred loaded

# Calculate R2 for training set
R2_train = calculate_R2(y_train2 , pred_train)

# Calculate R2 for test set
R2_test = calculate_R2(y_test , pred_test)

print(f"Model R2 for training set: {R2_train}")
print(f"Model R2 for test set: {R2_test}")
# #_____________________________________ IDW R2__________________________________

# # Calculate R2 for training set
# R2_trainI = calculate_R2(y_train2 - IDW_train)

# # Calculate R2 for test set
# R2_testI  = calculate_R2(y_test - IDW_test)

# print(f"IDW R2 for training set: {R2_trainI}")
# print(f"IDW R2 for test set: {R2_testI}")


# #_____________________________________ RBF R2__________________________________

# # Calculate R2 for training set
# R2_trainR = calculate_R2(y_train2 - RBF_train)

# # Calculate R2 for test set
# R2_testR  = calculate_R2(y_test - RBF_test)

# print(f"RBF R2 for training set: {R2_trainR}")
# print(f"RBF R2 for test set: {R2_testR}")


# #_____________________________________ Kriging R2__________________________________


# # Calculate R2 for training set
# R2_trainK = calculate_R2(y_train2 - kriging_train)

# # Calculate R2 for test set
# R2_testK  = calculate_R2(y_test - kriging_test)

# print(f"kriging R2 for training set: {R2_trainK}")
# print(f"kriging R2 for test set: {R2_testK}")

"""# **Mean Absolute Error (MAE)**"""

# Function to calculate Mean Absolute Error (MAE)
def calculate_MAE(y_true, y_pred):
    return mean_absolute_error(y_true, y_pred)
#_____________________________________ model MAE__________________________________

# Assuming you have y_train_true, y_train_pred, y_test_true, y_test_pred loaded

# Calculate MAE for training set
MAE_train = calculate_MAE(y_train2 , pred_train)

# Calculate MAE for test set
MAE_test = calculate_MAE(y_test , pred_test)

print(f"Model MAE for training set: {MAE_train}")
print(f"Model MAE for test set: {MAE_test}")
# #_____________________________________ IDW MAE__________________________________

# # Calculate MAE for training set
# MAE_trainI = calculate_MAE(y_train2 - IDW_train)

# # Calculate MAE for test set
# MAE_testI  = calculate_MAE(y_test - IDW_test)

# print(f"IDW MAE  for training set: {MAE_trainI}")
# print(f"IDW MAE  for test set: {MAE_testI}")


# #_____________________________________ RBF MAE __________________________________

# # Calculate MAE  for training set
# MAE _trainR = calculate_MAE (y_train2 - RBF_train)

# # Calculate MAE for test set
# MAE _testR  = calculate_MAE (y_test - RBF_test)

# print(f"RBF MAE  for training set: {MAE _trainR}")
# print(f"RBF MAE  for test set: {MAE _testR}")


# #_____________________________________ Kriging MAE __________________________________


# # Calculate MAE  for training set
# MAE _trainK = calculate_MAE (y_train2 - kriging_train)

# # Calculate MAE  for test set
# MAE _testK  = calculate_MAE (y_test - kriging_test)

# print(f"kriging MAE  for training set: {MAE _trainK}")
# print(f"kriging MAE  for test set: {MAE _testK}")

"""# **Perform statistical tests:**

T-test or ANOVA to compare the performance metrics between the CNN model and Kriging.
"""

# Perform statistical tests (t-tests or ANOVA)
#_______________________________Kriging_______________________________

#  t-test for RMSE
t_statistic, p_value = stats.ttest_ind(rmse_test, rmse_testK)
print("\nStatistical significance test (t-test) for RMSE:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")


#  t-test for R2

t_statistic, p_value = stats.ttest_ind(R2_test, R2_testK)
print("\nStatistical significance test (t-test) for R2:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

#  t-test for MAE

t_statistic, p_value = stats.ttest_ind(MAE_test, rmse_testK)
print("\nStatistical significance test (t-test) for MAE:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

#_______________________________IDW_______________________________

#  t-test for RMSE
t_statistic, p_value = stats.ttest_ind(rmse_test, rmse_testI)
print("\nStatistical significance test (t-test) for RMSE:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")


#  t-test for R2

t_statistic, p_value = stats.ttest_ind(R2_test, R2_testI)
print("\nStatistical significance test (t-test) for R2:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

#  t-test for MAE

t_statistic, p_value = stats.ttest_ind(MAE_test, MAE_testI)
print("\nStatistical significance test (t-test) for MAE:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

#_______________________________RBF_______________________________

#  t-test for RMSE
t_statistic, p_value = stats.ttest_ind(rmse_test, rmse_testR)
print("\nStatistical significance test (t-test) for RMSE:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")


#  t-test for R2

t_statistic, p_value = stats.ttest_ind(R2_test, R2_testR)
print("\nStatistical significance test (t-test) for R2:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")

#  t-test for MAE

t_statistic, p_value = stats.ttest_ind(MAE_test, MAE_testR)
print("\nStatistical significance test (t-test) for MAE:")
print(f"T-statistic: {t_statistic}")
print(f"P-value: {p_value}")